version: '3.8'
services:
  elgg:
    build:
      context: ./
      dockerfile: ./dockerfile
    ports:
      - '8080:80'
    depends_on:
      mysql_elgg_db:
        condition: service_healthy
     # mysql_muse_db:
    #    condition: service_healthy
    env_file:
      - path: ./elgg.env
    volumes:
      - elgg_data:/data/elgg_data:rw
      - ./elgg_config_container:/var/www/html/elgg_config

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  mysql_elgg_db:
    hostname: mysql_elgg_db
    image: mysql:8.3
    ports:
      - '3306:3306'
    env_file:
      - path: ./elgg.env
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    volumes:
      - elgg_db_data:/var/lib/mysql

  # mysql_muse_db:
  #   hostname: mysql_muse_db
  #   image: mysql:8.3
  #   ports:
  #     - '3307:3307'
  #   env_file:
  #     - path: ./muse.env
  #   healthcheck:
  #     test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
  #     timeout: 20s
  #     retries: 10
  #   volumes:
  #     - muse_db_data:/var/lib/mysql

volumes:
  # Upload folder for user uploads etc
  elgg_data: 
  elgg_db_data: 
  muse_data:
  #muse_db_data:
  mongodb_data:
