version: '3'
services:
  elgg:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/htmldocker
  
  db:
    image: mysql:5.6 
    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: null
      MYSQL_DATABASE: workshop1
      MYSQL_USER: muse
      MYSQL_PASSWORD: null


# environment:
#     MYSQL_USER: root
#     MYSQL_PASS: 
#     ELGG_USERNAME: admin
#     ELGG_PASSWORD: admin1
#     ELGG_WWW_ROOT: http://localhost:8000
# mysql:
#   image: mysql:5.6  
#   environment:
#     MYSQL_DATABASE: workshop1
#     MYSQL_ROOT_PASSWORD: 